frame_period: 5.0
pitch_shift: 1.15
intensity_shift: 2.2
pitch_scale: [0.5, 0.75, 1.25, 1.5]
intensity_scale: [0.5, 0.75, 1.25, 1.5]
vocal_tract_length: [0.6, 0.8, 1.2, 1.4]
intensity_scale_by_vowel: false